version: "3.8"

services:
  app:
    container_name: surgery-order-app
    image: surgery-order-app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000